### PR TITLE
removed the sharma dataset and updated the sizes of the proteome tool…

### PR DESCRIPTION
**Pull request by TjobberTjob**
…s RT dataset

### CODE REVIEW

**Comment by edeutsch** [comment]
Why remove the Sharma dataset?

**Comment by TjobberTjob** [comment]
I thought we agreed it wasnt ideal to re-host a dataset where we know no metadata or publication information.

**Comment by edeutsch** [comment]
I was under the impression that we just decided not to explicitly mention it and thus be obliged to cite it in the manuscript. But I didn't think we would remove it completely from the repo? But maybe I wasn't following the conversation..

**Comment by TjobberTjob** [comment]
We mentioned removing it from the repo, as otherwise we're opening ourselves up to have a potential influx of undescribed datasets, and that we should expect some level of metadata and information from the datasets we host. I think this makes sense to bring up with the others on Slack

**Pull request merged**
